// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeCFRkCXXIiqQITqLdIDDMT6K4GZZCMmQ',
    appId: '1:947502828959:web:e2dc3ed13e735081cac1aa',
    messagingSenderId: '947502828959',
    projectId: 'simplelogin-cc7b2',
    authDomain: 'simplelogin-cc7b2.firebaseapp.com',
    databaseURL: 'https://simplelogin-cc7b2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'simplelogin-cc7b2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALsG-bSdXKuEKzcw3uVC2lCsIGn-4SzEY',
    appId: '1:947502828959:android:993344e20863c5a3cac1aa',
    messagingSenderId: '947502828959',
    projectId: 'simplelogin-cc7b2',
    databaseURL: 'https://simplelogin-cc7b2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'simplelogin-cc7b2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2oEigJoRV9gaJvuoJQN9t3ubkbV1fvy8',
    appId: '1:947502828959:ios:476802c4af5cf41ecac1aa',
    messagingSenderId: '947502828959',
    projectId: 'simplelogin-cc7b2',
    databaseURL: 'https://simplelogin-cc7b2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'simplelogin-cc7b2.appspot.com',
    iosBundleId: 'com.example.login3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2oEigJoRV9gaJvuoJQN9t3ubkbV1fvy8',
    appId: '1:947502828959:ios:47eaf9f0f1dd871fcac1aa',
    messagingSenderId: '947502828959',
    projectId: 'simplelogin-cc7b2',
    databaseURL: 'https://simplelogin-cc7b2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'simplelogin-cc7b2.appspot.com',
    iosBundleId: 'com.example.login3.RunnerTests',
  );
}
